const assert = require("node:assert/strict");
const fs = require("node:fs");

const page = fs.readFileSync(`${__dirname}/../index.html`, "utf8");

assert.match(page, /if \(result\.health < 1\) result\.health = 1/);
assert.match(page, /exact approaching-hard-cap formula is not yet known/);
assert.equal((page.match(/name: "(?:Encrypted Archive|Goblet of the Sun|HC Armor Plating|Heart of Cinders|Essence of Malice|Wheel of Reincarnation|Sealed Megium)"/g) || []).length, 7);
assert.match(page, /const RUNE_SLOTS = \["Penumbra", "Antumbra", "Umbra", "Eclipse"\]/);
assert.equal((page.match(/id: "(?:fragility|smolder|fever|conductor|profane|divine|rot|tremor|drain|shedding|anaemia|hypoxia|light|asthma)", name:/g) || []).length, 14);
assert.doesNotMatch(page, /artifactMultiplier|Gambit ×/);
assert.match(page, /const totalMultiplier = artifactCount/);
assert.match(page, /buildOptions\.artifacts\[card\.dataset\.id\] = Math\.min\(100/);
assert.match(page, /Shown defense:.*100% ÷ \$\{n\(calculation\.damageTaken\)\} = \$\{n\(calculation\.defense\)\}/);
assert.doesNotMatch(page, /Shown defense:.*÷ 100%/);
assert.match(page, /artifacts: ARTIFACTS\.map/);
assert.match(page, /runes: buildOptions\.runes\.map/);
assert.match(page, /curses: buildOptions\.curses\.map/);
assert.match(page, /id: "hypoxia", name: "Hypoxia", effect: "Healing Received -15% per stack\.", stats: p => \(\{ healingReceived: -15 \* p \}\)/);
assert.match(page, /id: "shedding", name: "Shedding", effect: "Overall Defense -7% per stack\.", stats: p => \(\{ overallDefense: -7 \* p \}\)/);
assert.match(page, /id="reset-build"[^>]*>Reset build<\/button>/);
assert.match(page, /data-remove-rune="\$\{index\}"/);
assert.match(page, /buildOptions\.artifacts = \{\};[\s\S]*buildOptions\.runes = RUNE_SLOTS\.map\(\(\) => null\);[\s\S]*buildOptions\.curses = RUNE_SLOTS\.map\(\(\) => null\);/);
assert.equal((page.match(/\{ id: "(?:fire|frost|lightning|physical|luminous|shadow)", name:/g) || []).length, 6);
assert.match(page, /name="twinmage-\$\{hand\}"/);
assert.match(page, /twinmagePrimary: TWINMAGE_ELEMENTS\.some/);
assert.match(page, /twinmageSecondary: TWINMAGE_ELEMENTS\.some/);
assert.match(page, /name="twinmage-\$\{hand\}-damage"/);
assert.match(page, /twinmagePrimaryDamage: saved\.twinmagePrimaryDamage !== false/);
assert.match(page, /twinmageSecondaryDamage: saved\.twinmageSecondaryDamage !== false/);
assert.match(page, /if \(!buildOptions\.twinmagePrimaryDamage && !buildOptions\.twinmageSecondaryDamage\) buildOptions\.twinmagePrimaryDamage = true;/);
assert.match(page, /if \(!buildOptions\.twinmagePrimaryDamage && !buildOptions\.twinmageSecondaryDamage\)/);
assert.match(page, /buildOptions\.twinmagePrimary = "fire";[\s\S]*buildOptions\.twinmageSecondary = "lightning";[\s\S]*buildOptions\.twinmagePrimaryDamage = true;[\s\S]*buildOptions\.twinmageSecondaryDamage = true;/);
assert.match(page, /id="calculation-content"/);
assert.match(page, /function renderCalculations\(\)/);
assert.match(page, /const uptimePercent = value =>/);
assert.match(page, /formatted\.endsWith\("\.00"\) \? formatted\.slice\(0, -3\) : formatted/);
assert.match(page, /value: hand => uptimePercent\(hand\.damage\.uptime\)/);
assert.match(page, /const overallMultiplier = Number\(latestCalculation\.stats\.overallDamage \|\| 0\) \/ 100;/);
assert.match(page, /const elementalMultiplier = Number\(latestCalculation\.stats\[hand\.element\.damageStat\] \|\| 0\) \/ 100;/);
assert.match(page, /\.filter\(hand => hand\.enabled\)/);
assert.match(page, /calculatedHands\.length === 1 \? "single-hand" : "dual-hand"/);
assert.match(page, /data-element="\$\{hand\.element\.id\}"/);
assert.match(page, /physical.*damageStat: "physicalDamage"/);
assert.match(page, /lightning.*damageStat: "electricDamage"/);
assert.match(page, /handName: "Flaming Hand", baseDamage: 30/);
assert.match(page, /handName: "Ice Hand", baseDamage: 30/);
assert.match(page, /handName: "Electric Hand", baseDamage: 30/);
assert.match(page, /handName: "Wind Blade", baseDamage: 30/);
assert.match(page, /handName: "Divine Hand", baseDamage: 35/);
assert.match(page, /handName: "Profane Hand", baseDamage: 20/);
assert.match(page, /const attackSpeedBase = hands\.length === 1 \? 1\.4 : 0\.8;/);
assert.match(page, /const attackSpeedMultiplier = Number\(latestCalculation\.stats\.attackSpeed \|\| 0\) \/ 100;/);
assert.match(page, /if \(stat === "attackSpeed"\) return `\$\{Number\(Number\(value\)\.toFixed\(2\)\)\}%`;/);
assert.match(page, /const instancesPerSecond = attackSpeedBase \* attackSpeedMultiplier;/);
assert.match(page, /hand\.element\.baseDamage \* overallMultiplier \* elementalMultiplier \* criticalMultiplier/);
assert.match(page, /const totalDamage = Math\.round\(unroundedDamage\);/);
assert.match(page, /const dps = totalDamage \* instancesPerSecond;/);
assert.match(page, /const totalDps = dps \* uptime;/);
assert.match(page, /data-exact-value="\$\{escapeHtml\(String\(row\.exact\(hand\)\)\)\}"/);
assert.match(page, /label: "Instance Rate"/);
assert.doesNotMatch(page, /damage-source/);
assert.doesNotMatch(page, /Hand damage overview|damage-calculation-note|damage-calculation-head/);
assert.match(page, /\.damage-table \.damage-data-col \{ width: 72px; \}/);
assert.match(page, /<col class="damage-label-col"><col class="damage-data-col" span="\$\{damageColumns\.length\}">/);
assert.match(page, /const criticalChancePercent = Number\(latestCalculation\.stats\.criticalChance \|\| 0\);/);
assert.match(page, /const criticalDamagePercent = Number\(latestCalculation\.stats\.criticalDamage \|\| 0\);/);
assert.match(page, /const criticalChance = Math\.max\(0, criticalChancePercent\) \/ 100;/);
assert.match(page, /const effectiveCriticalMultiplier = \(criticalDamageMultiplier - 1\) \* criticalChance \+ 1;/);
assert.match(page, /\.filter\(hand => hand\.element\.canCrit\)[\s\S]*const criticalHitsPerSecond = criticalInstanceRate \* criticalChance;/);
assert.match(page, /const criticalMultiplier = hand\.element\.canCrit \? effectiveCriticalMultiplier : 1;/);
assert.match(page, /label: "Crits per second"/);
assert.match(page, /<th colspan="2">Critical hits<\/th>/);
assert.equal((page.match(/statusChances: \{ burning: 0\.10 \}/g) || []).length, 1);
assert.match(page, /const BURNING = \{ baseStacks: 20, stacksPerSticky: 2, durationPerStack: 0\.5, bossApplicationPenalty: 3 \};/);
assert.match(page, /chance \/ attackSpeedMultiplier/);
assert.match(page, /sum \+ hand\.damage\.instancesPerSecond \* hand\.effectiveStatusChances\.burning/);
assert.match(page, /const burningStacks = BURNING\.baseStacks \+ count\("Sticky"\) \* BURNING\.stacksPerSticky;/);
assert.match(page, /const burningDuration = burningStacks \* BURNING\.durationPerStack;/);
assert.match(page, /Math\.min\(1, burningDuration \/ burningInterval\)/);
assert.match(page, /burningHands\.length \? `<section class="status-table-wrap" data-status="burning">/);
assert.match(page, /<th colspan="2">Status: Burning<\/th>/);
assert.match(page, /<div class="calculation-secondary">[\s\S]*crit-table-wrap[\s\S]*status-table-wrap/);
assert.match(page, /id: "burning", handName: "Burning", baseDamage: 25, damageStat: "fireDamage", canCrit: false, statusChances: \{\}/);
assert.match(page, /const instancesPerSecond = 0\.5;/);
assert.match(page, /const uptime = burningUptime;/);
assert.match(page, /const statusColumns = \[burningColumn, bleedingColumn\]\.filter\(Boolean\)/);
assert.match(page, /const triggeredColumns = \[chargedStrikeColumn\]\.filter\(Boolean\);/);
assert.match(page, /const damageColumns = \[\.\.\.attackSources, \.\.\.triggeredColumns, \.\.\.statusColumns\];/);
assert.match(page, /const masteryColumns = count\("Twinmage_Mastery"\) > 0 \? calculatedHands\.map/);
assert.match(page, /baseDamage: hand\.element\.baseDamage \* 0\.25/);
assert.match(page, /const instancesPerSecond = hand\.damage\.instancesPerSecond;/);
assert.match(page, /baseStatusChances: \{ \.\.\.hand\.baseStatusChances \}/);
assert.match(page, /effectiveStatusChances: \{ \.\.\.hand\.effectiveStatusChances \}/);
assert.match(page, /const attackSources = \[\.\.\.calculatedHands, \.\.\.masteryColumns\];/);
assert.match(page, /const burningHands = attackSources\.filter/);
assert.match(page, /const bleedingHands = attackSources\.filter/);
assert.match(page, /const chargedStrikeStacks = count\("Charged_Strike"\);/);
assert.match(page, /baseDamage: 15 \+ Math\.max\(0, chargedStrikeStacks - 1\) \* 10/);
assert.match(page, /damageStat: "physicalDamage", canCrit: false, statusChances: \{\}/);
assert.match(page, /const instancesPerSecond = criticalHitsPerSecond;/);
assert.match(page, /position: "Upgrade effect", columnKey: "charged-strike"/);
assert.match(page, /hand\.isTriggeredEffect \? \["calc:crit:rate"\]/);
assert.match(page, /sourceUpgradeId: "Twinmage_Mastery"/);
assert.match(page, /sourceUpgradeId: "Charged_Strike"/);
assert.match(page, /data-calculation-source-upgrade=/);
assert.match(page, /calculation-tooltip-upgrade-icon/);
assert.match(page, /sourceUpgrade\.effect/);
assert.match(page, /sourceIcon: hand\.element\.image/);
assert.match(page, /data-calculation-source-icon=/);
assert.match(page, /calculation-tooltip-source-icon/);
assert.match(page, /hand\.element\.canCrit \? twoDecimals\(hand\.damage\.criticalMultiplier\) : "-"/);
assert.match(page, /hand\.isStatusGroupStart \? "status-group-start" : ""/);
assert.match(page, /\.damage-column\.status-group-start \{ border-left: 3px solid rgba\(var\(--class-rgb\), \.72\); \}/);
assert.equal((page.match(/statusChances: \{ bleeding: 0\.10 \}/g) || []).length, 1);
assert.match(page, /const BLEEDING = \{ baseStacks: 16, stacksPerSticky: 2, durationPerStack: 0\.8, bossApplicationPenalty: 3 \};/);
assert.match(page, /burning: \{ upgradeId: "Fire_Aspect", chancePerStack: 0\.05 \}/);
assert.match(page, /bleeding: \{ upgradeId: "Cutting_Edge", chancePerStack: 0\.10 \}/);
assert.match(page, /frozen: \{ upgradeId: "Frost_Aspect", chancePerStack: 0\.05 \}/);
assert.match(page, /weakened: \{ upgradeId: "Luminous_Aspect", chancePerStack: 0\.05 \}/);
assert.match(page, /breached: \{ upgradeId: "Shadow_Aspect", chancePerStack: 0\.05 \}/);
assert.doesNotMatch(page, /paralyzed: \{ upgradeId:/);
assert.match(page, /chance \+ \(bonus \? count\(bonus\.upgradeId\) \* bonus\.chancePerStack : 0\)/);
assert.match(page, /Object\.entries\(baseStatusChances\)/);
assert.match(page, /hand\.baseStatusChances\.burning \* 100/);
assert.match(page, /hand\.baseStatusChances\.bleeding \* 100/);
assert.match(page, /const burningRawUptime = bossAdjustedBurningRate > 0 \? burningDuration \/ burningInterval : 0;/);
assert.match(page, /const bleedingRawUptime = bossAdjustedBleedingRate > 0 \? bleedingDuration \/ bleedingInterval : 0;/);
assert.match(page, /status-uncapped-uptime/);
assert.match(page, /`100% <span class="status-uncapped-uptime">/);
assert.match(page, /capped at 100%/);
assert.match(page, /\.damage-column\[data-element="physical"\] \{ --damage-color: var\(--physical\); \}/);
assert.doesNotMatch(page, /\.stat-row\[data-stat="physicalDamage"\] \.value \{ color: var\(--physical\); \}/);
assert.match(page, /\.stat-list \{[\s\S]*?font-style: normal;/);
assert.match(page, /sum \+ hand\.damage\.instancesPerSecond \* hand\.effectiveStatusChances\.bleeding/);
assert.match(page, /const bleedingStacks = BLEEDING\.baseStacks \+ count\("Sticky"\) \* BLEEDING\.stacksPerSticky;/);
assert.match(page, /const bleedingDuration = bleedingStacks \* BLEEDING\.durationPerStack;/);
assert.match(page, /Math\.min\(1, bleedingDuration \/ bleedingInterval\)/);
assert.match(page, /id: "bleeding", name: "Physical", handName: "Bleeding", baseDamage: 25, damageStat: "physicalDamage", canCrit: false/);
assert.match(page, /const instancesPerSecond = 0\.8;/);
assert.match(page, /<th colspan="2">Status: Bleeding<\/th>/);
assert.equal((page.match(/statusChances: \{ (?:frozen|paralyzed|weakened|breached): 0\.10 \}/g) || []).length, 4);
assert.match(page, /const NON_DAMAGE_STATUS_DEFINITIONS = \[/);
assert.match(page, /const nonDamageStatuses = NON_DAMAGE_STATUS_DEFINITIONS\.map/);
assert.match(page, /\.filter\(status => status\.sources\.length\)/);
assert.match(page, /const nonDamageStatusRows = status =>/);
assert.match(page, /label: "Stacks per application", value: "\?"/);
assert.match(page, /label: "Uptime", value: "\?"/);
assert.match(page, /Status: \$\{escapeHtml\(status\.name\)\}/);
assert.match(page, /id: "frozen", name: "Frozen", bossApplicationPenalty: 10/);
assert.match(page, /id: "paralyzed", name: "Paralyzed", bossApplicationPenalty: 10/);
assert.match(page, /id: "weakened", name: "Weakened", bossApplicationPenalty: 2/);
assert.match(page, /id: "breached", name: "Breached", bossApplicationPenalty: 2/);
assert.equal((page.match(/Bosses likely build up resistance against this status effect over time!/g) || []).length, 2);
assert.match(page, /class="status-note" colspan="2"/);
assert.match(page, /const combinedTotalDps = damageColumns\.reduce\(\(sum, hand\) => sum \+ hand\.damage\.totalDps, 0\);/);
assert.match(page, /<th scope="row" class="damage-combined-label">Combined DPS<\/th>/);
assert.match(page, /calculationAttributes\("damage:combined:total-dps"/);
assert.match(page, /const combinedDpsBreakdown = Object\.values\(damageColumns\.reduce/);
assert.match(page, /data-calculation-damage-type=/);
assert.match(page, /data-calculation-breakdown=/);
assert.match(page, /calculation-damage-breakdown-row/);
assert.match(page, /id="calculation-tooltip" role="tooltip"/);
assert.match(page, /data-calculation-key=/);
assert.match(page, /data-calculation-formula=/);
assert.match(page, /data-calculation-refs=/);
assert.match(page, /refs: \(\) => \["stat:overallDamage"\]/);
assert.match(page, /refs: hand => hand\.element\.canCrit \? \["calc:crit:effective"\] : \[\]/);
assert.match(page, /function highlightCalculationReferences\(refs\)/);
assert.match(page, /function positionCalculationTooltip\(clientX, clientY\)/);
assert.match(page, /\.calculation-reference/);
assert.match(page, /const sourceFormula = hand =>/);
assert.match(page, /Crit: \$\{hand\.element\.canCrit \? "Yes" : "No"\}/);
assert.match(page, /% ÷ \$\{twoDecimals\(attackSpeedMultiplier \* 100\)\}% AS = \$\{twoDecimals\(hand\.effectiveStatusChances\[status\] \* 100\)\}%/);
assert.match(page, /hand\.baseStatusChances\.burning \* 100\).*attackSpeedMultiplier \* 100/);
assert.match(page, /calculationAttributes\(`source:\$\{hand\.columnKey\}`, sourceFormula\(hand\)\)/);
assert.match(page, /tooltip\.style\.setProperty\("--tooltip-accent", accent\)/);
assert.match(page, /calculation-tooltip-head/);
assert.match(page, /calculation-tooltip-expression/);
assert.match(page, /Non-crit: \$\{hand\.element\.baseDamage\}/);
assert.match(page, /Crit: \$\{twoDecimals\(bareDamage\)\} × \$\{twoDecimals\(criticalDamageMultiplier\)\}/);
assert.match(page, /"calc:crit:damage", "stat:criticalDamage"/);
assert.match(page, /id: "physical", name: "Physical", handName: "Charged Strike"/);

console.log("Build option regression tests passed.");
