const assert = require("node:assert/strict");
const fs = require("node:fs");

const page = fs.readFileSync(`${__dirname}/../index.html`, "utf8");
assert.match(page, /<title>AdventureLuna's Ecliptica Build Forge<\/title>/);
assert.match(page, /<h1>AdventureLuna's Ecliptica Build Forge<\/h1>/);
assert.doesNotMatch(page, /Left-click to add an artifact/);
for (const icon of ["Nekomancer-Primary-2.png", "Neko_Zombie.png", "Neko_Balloon.png", "Neko_Ballista.png", "Spellsword-Primary.png", "Spellsword-Secondary.png"]) {
  assert.ok(fs.existsSync(`${__dirname}/../pictures/${icon}`), `Missing class ability icon: ${icon}`);
}

assert.match(page, /if \(result\.health < 1\) result\.health = 1/);
assert.match(page, /exact approaching-hard-cap formula is not yet known/);
assert.equal((page.match(/name: "(?:Encrypted Archive|Goblet of the Sun|HC Armor Plating|Heart of Cinders|Essence of Malice|Wheel of Reincarnation|Sealed Megium)"/g) || []).length, 7);
assert.match(page, /const RUNE_SLOTS = \["Penumbra", "Antumbra", "Umbra", "Eclipse"\]/);
assert.equal((page.match(/id: "(?:fragility|smolder|fever|conductor|profane|divine|rot|tremor|drain|shedding|anaemia|hypoxia|light|asthma)", name:/g) || []).length, 14);
assert.doesNotMatch(page, /artifactMultiplier|Gambit ×/);
assert.match(page, /const totalMultiplier = artifactCount/);
assert.match(page, /buildOptions\.artifacts\[card\.dataset\.id\] = Math\.min\(100/);
assert.match(page, /Shown defense:.*100% ÷ \$\{n\(calculation\.damageTaken\)\} = \$\{n\(calculation\.defense\)\}/);
assert.doesNotMatch(page, /Shown defense:.*÷ 100%/);
assert.match(page, /artifacts: ARTIFACTS\.map/);
assert.match(page, /runes: buildOptions\.runes\.map/);
assert.match(page, /curses: buildOptions\.curses\.map/);
assert.match(page, /id: "hypoxia", name: "Hypoxia", effect: "Healing Received -15% per stack\.", stats: p => \(\{ healingReceived: -15 \* p \}\)/);
assert.match(page, /id: "shedding", name: "Shedding", effect: "Overall Defense -7% per stack\.", stats: p => \(\{ overallDefense: -7 \* p \}\)/);
assert.match(page, /id="reset-build"[^>]*>Reset build<\/button>/);
assert.match(page, /id="reset-configuration"[^>]*>Reset configuration<\/button>/);
assert.match(page, /data-remove-rune="\$\{index\}"/);
assert.match(page, /buildOptions\.artifacts = \{\};[\s\S]*buildOptions\.runes = RUNE_SLOTS\.map\(\(\) => null\);[\s\S]*buildOptions\.curses = RUNE_SLOTS\.map\(\(\) => null\);/);
assert.match(page, /const validIds = new Set\(U\.map\(upgrade => upgrade\.id\)\);/);
assert.match(page, /Number\.isInteger\(Number\(value\)\) && Number\(value\) > 0/);
assert.match(page, /function safeSetStorage\(key, value\)/);
assert.match(page, /localStorage\.removeItem\(key\);[\s\S]*localStorage\.setItem\(key, value\);/);
assert.equal((page.match(/\{ id: "(?:fire|frost|lightning|physical|luminous|shadow)", name:/g) || []).length, 6);
assert.doesNotMatch(page, /id: "fire"[^\n]*instanceRate:/);
assert.match(page, /const attackSpeedBase = hands\.length === 1 \? 1\.4 : 0\.8;/);
assert.match(page, /const baseInstanceRate = hand\.element\.instanceRate \|\| attackSpeedBase;/);
assert.match(page, /twoDecimals\(hand\.baseInstanceRate\).*twoDecimals\(attackSpeedMultiplier\).*twoDecimals\(hand\.handAttackSpeedMultiplier\)/);
assert.match(page, /name="twinmage-\$\{hand\}"/);
assert.match(page, /twinmagePrimary: TWINMAGE_ELEMENTS\.some/);
assert.match(page, /twinmageSecondary: TWINMAGE_ELEMENTS\.some/);
assert.match(page, /name="twinmage-\$\{hand\}-damage"/);
assert.match(page, /twinmagePrimaryDamage: saved\.twinmagePrimaryDamage !== false/);
assert.match(page, /twinmageSecondaryDamage: saved\.twinmageSecondaryDamage !== false/);
assert.match(page, /if \(!buildOptions\.twinmagePrimaryDamage && !buildOptions\.twinmageSecondaryDamage\) buildOptions\.twinmagePrimaryDamage = true;/);
assert.match(page, /if \(!buildOptions\.twinmagePrimaryDamage && !buildOptions\.twinmageSecondaryDamage\)/);
assert.match(page, /buildOptions\.twinmagePrimary = "fire";[\s\S]*buildOptions\.twinmageSecondary = "lightning";[\s\S]*buildOptions\.twinmagePrimaryDamage = true;[\s\S]*buildOptions\.twinmageSecondaryDamage = true;/);
assert.match(page, /Berserker’s Soul \(Melee\)/);
assert.match(page, /Berserker’s Soul \(Ranged\)/);
assert.match(page, /melee: \{ id: "Berserker's_Soul_Melee", classes: \["Spellsword", "Fistmage", "Spellhammer", "Shield Mage"\]/);
assert.match(page, /ranged: \{ id: "Berserker's_Soul_Ranged", classes: \["Twinmage", "Gunmancer", "Thaumaturge"\]/);
assert.match(page, /damagePenalty: -20, attackSpeedPenalty: -40, damageAt70: 45, attackSpeedAt70: 90, regenerationAt70: -50/);
assert.match(page, /damagePenalty: -10, attackSpeedPenalty: -20, damageAt70: 22\.5, attackSpeedAt70: 45, regenerationAt70: 0, spreadAt70: 2/);
assert.match(page, /\["projectileSpread","Projectile Spread"\]/);
assert.match(page, /\["poisonDamage","Poison Damage","poison"\], \[null\], \["projectileSpread","Projectile Spread"\]/);
assert.doesNotMatch(page, /\["projectileSpeed","Projectile Speed"\], \["projectileSpread","Projectile Spread"\]/);
assert.match(page, /\["projectileSpread", "Thaumaturge_Splitshot", 2\.5\], \["projectileSpread", "Hawkeye", -1\]/);
assert.match(page, /if \(result\.projectileSpread < 0\) result\.projectileSpread = 0/);
assert.match(page, /berserkerSoulStacks: Math\.max\(0, Math\.floor/);
assert.match(page, /const defaultBerserkerStacks = \(Number\(counts\[savedBerserkerVariant\?\.id\]\) \|\| 0\) \* 70/);
assert.match(page, /function berserkerMaximumStacks\(upgradeCount = berserkerUpgradeCount\(\)\)/);
assert.match(page, /const stackRatio = previousMaximum > 0 \? clampBerserkerStacks\(previous\) \/ previousMaximum : 1/);
assert.match(page, /name="berserker-soul-stacks" min="0" max="\$\{maximum\}"/);
assert.match(page, /const stackRatio = previousMaximum > 0 \? Math\.min\(previousMaximum,[\s\S]*: 1;/);
assert.match(page, /buildOptions\.berserkerSoulStacks = Math\.round\(stackRatio \* nextMaximum\)/);
assert.match(page, /buildOptions\.berserkerSoulStacks = berserkerMaximumStacks\(rawCount\(berserkerVariantForClass\(\)\?\.id\)\)/);
assert.match(page, /const GUNMANCER_ABILITIES =/);
assert.match(page, /name: "VA-11 Blast Cannon"/);
assert.match(page, /name: "Kinetic Fletchette"/);
assert.match(page, /name: "Firebomb"/);
assert.match(page, /name: "Photon Condenser"/);
assert.match(page, /name: "Antimatter Accelerator"/);
assert.match(page, /id: "firebomb"[\s\S]*?status: \{ id: "burning", name: "Burning", chance: \.10 \}/);
assert.match(page, /iconFile: "Gunmancer-Primary\.png"/);
assert.match(page, /iconFile: "Gunmancer-Flechette\.png"/);
assert.match(page, /iconFile: "Gumancer-Photon-Cannon\.png"/);
assert.match(page, /iconFile: "Gumancer-Airblast\.png"/);
assert.match(page, /interval: 2, attackSpeedAffected: true/);
assert.match(page, /interval: \.25, attackSpeedAffected: true/);
assert.match(page, /interval: 1 \/ 0\.33, attackSpeedAffected: true/);
assert.match(page, /status: \{ id: "burning", name: "Burning", chance: null \}/);
assert.match(page, /name: "Impact explosion", element: "electric", damage: 25, projectiles: 1, canCrit: true/);
assert.match(page, /name: "Wide explosion", element: "fire", damage: 50, projectiles: 1, canCrit: true/);
assert.match(page, /The Japanese wiki reports 0\.5 shots\/s/);
assert.match(page, /The Japanese page gives 0\.5\/s for both primaries/);
assert.match(page, /damage: 50, projectiles: 1/);
assert.match(page, /damage: 75, projectiles: 1/);
assert.match(page, /damage: 8, projectiles: 5, chargedProjectiles: \(\) => 3 \+ count\("Gunmancer_Proficiency_Antimatter"\)/);
assert.match(page, /name: "Airblast"/);
assert.match(page, /cooldown: 12, chargedMultiplier: 2/);
assert.match(page, /function renderGunmancerConfiguration/);
assert.match(page, /This gets calculated as using the charged shot on cooldown in addition to whatever is selected above/);
assert.match(page, /function gunmancerDpsGroup()/);
assert.match(page, /name="gunmancer-dps" value="primary"/);
assert.match(page, /name="gunmancer-dps" value="secondary"/);
assert.match(page, /buildOptions\.gunmancerPrimaryDamage = group === "primary"/);
assert.match(page, /buildOptions\.gunmancerSecondaryDamage = group === "secondary"/);
assert.match(page, /gunmancerDpsToggle\.checked = true/);
assert.match(page, /function buildGunmancerSourceModel/);
assert.match(page, /selectedClass === "Gunmancer" \? buildGunmancerSourceModel\(stats\)/);
assert.match(page, /if \(selectedClass === "Gunmancer"\) \{\s*renderGunmancerConfiguration/);
assert.match(page, /const THAUMATURGE_PRIMARY = \{/);
assert.match(page, /id: "foul-pustule"/);
assert.match(page, /name: "Foul Pustule"/);
assert.match(page, /iconUrl: "pictures\/Thaumaturge-Primary-c\.png"/);
assert.match(page, /\|pictures\\\/\)\/i\.test\(sourceIcon\)/);
assert.match(page, /name: ability\.components\.length === 1 \? ability\.name : component\.name/);
assert.match(page, /damage-table single-hand shared-ability-table/);
assert.match(page, /pictures\/Thaumaturge-Life-Energy-a\.png/);
assert.match(page, /pictures\/Thaumaturge-Secondary\.png/);
assert.match(page, /pictures\/Thaumaturge-Utility\.png/);
assert.match(page, /interval: 1 \/ \.75/);
assert.match(page, /status: \{ id: "poisoned", name: "Poisoned", chance: \.10 \}/);
assert.match(page, /damage: 30, projectiles: \(\) => 1 \+ count\("Thaumaturge_Splitshot"\)/);
assert.match(page, /function renderThaumaturgeConfiguration/);
assert.match(page, /function abilityDamageSourceSpecs/);
assert.match(page, /function buildThaumaturgeSourceModel/);
assert.match(page, /selectedClass === "Thaumaturge" \? buildThaumaturgeSourceModel\(stats\)/);
assert.match(page, /const NEKOMANCER_PRIMARY = \{/);
assert.match(page, /name: "Staff of Feline Mortality"/);
assert.match(page, /iconUrl: "pictures\/Nekomancer-Primary-2\.png"/);
assert.match(page, /interval: 1 \/ \.6/);
assert.match(page, /status: \{ id: "breached", name: "Breached", chance: \.10 \}/);
assert.match(page, /element: "shadow", damage: 20, projectiles: 1, canCrit: true/);
assert.match(page, /const NEKOMANCER_MINION_LIMIT = 3/);
assert.match(page, /name: "Zombie Kitty"[^\n]*damage: 25[^\n]*baseActivationRate: \.6[^\n]*chance: \.05/);
assert.match(page, /name: "Balloon Kitty"[^\n]*damage: 36[^\n]*baseActivationRate: \.4[^\n]*chance: \.10/);
assert.match(page, /name: "Ballista Kitty"[^\n]*damage: 25[^\n]*baseActivationRate: \.5[^\n]*chance: \.10/);
assert.match(page, /function normalizeNekomancerMinions\(value\)/);
assert.match(page, /nekomancerMinions: normalizeNekomancerMinions\(saved\.nekomancerMinions\)/);
assert.match(page, /nekomancerSouls: Math\.min\(5/);
assert.match(page, /function renderNekomancerConfiguration\(content\)/);
assert.match(page, /data-nekomancer-minion-action="add"/);
assert.match(page, /name="nekomancer-souls" min="0" max="5"/);
assert.match(page, /function buildNekomancerSourceModel\(stats\)/);
assert.match(page, /minion\.baseActivationRate \* selected \* attackSpeedMultiplier/);
assert.match(page, /selectedClass === "Nekomancer" \? buildNekomancerSourceModel\(stats\)/);
assert.match(page, /2 \* nekomancerMasteryStacks \* nekomancerSouls/);
assert.match(page, /20 \* nekomancerMasteryStacks \* nekomancerSouls/);
assert.match(page, /const SPELLSWORD_PRIMARY = \{/);
assert.match(page, /name: "Telekinetic Strike", iconUrl: "pictures\/Spellsword-Primary\.png"/);
assert.match(page, /element: "physical", damage: 65, baseActivationRate: 1/);
assert.match(page, /const SPELLSWORD_SECONDARY = \{/);
assert.match(page, /name: "Piercing Strike", iconUrl: "pictures\/Spellsword-Secondary\.png"/);
assert.match(page, /minimumCharge: \.170, optimalCharge: \.5, maximumCharge: 5\.075/);
assert.match(page, /function renderSpellswordConfiguration\(content\)/);
assert.match(page, /name="spellsword-dps" value="\$\{value\}"/);
assert.match(page, /function buildSpellswordSourceModel\(stats\)/);
assert.match(page, /selectedClass === "Spellsword" \? buildSpellswordSourceModel\(stats\)/);
assert.match(page, /Math\.round\(170\.70 - 97\.33 \* Math\.exp\(-\.8927 \* clampedCharge\)\)/);
assert.match(page, /return \.5 \* spellswordPiercingDamage\(chargeTime\) \/ 170/);
assert.match(page, /<span>Cooldown<\/span><strong>\$\{formatNumber\(SPELLSWORD_SECONDARY\.cooldown\)\}s<\/strong>/);
assert.match(page, /id: "spellsword-whirlwind"/);
assert.match(page, /function changeClass\(nextClass\)/);
assert.match(page, /dpsRankingRun \+= 1;/);
assert.match(page, /restoreCounts\(dpsRankingSnapshot\);/);
assert.match(page, /\$\("#configuration-content"\)\.replaceChildren\(\);/);
assert.match(page, /\$\("#calculation-content"\)\.replaceChildren\(\);/);
assert.match(page, /changeClass\(event\.target\.value\);/);
assert.match(page, /label: "Projectiles \/ Shot"/);
assert.match(page, /const DAMAGE_STATUS_DEFINITIONS = \{/);
assert.match(page, /poisoned: \{ id: "poisoned", name: "Poison", baseDamage: 30, damageStat: "poisonDamage", tickInterval: \.75, baseStacks: 8, stacksPerSticky: 2, durationPerStack: \.75/);
assert.match(page, /damageScaling: \.75/);
assert.match(page, /EclipticaCalculationEngine\.calculate/);
assert.match(page, /function renderUnifiedCalculations/);
assert.match(page, /damageScaling: \.75/);
assert.match(page, /status\.rawUptime > 1 \? `100% <span class="status-uncapped-uptime">/);
assert.match(page, /row\.valueHtml \|\| escapeHtml\(row\.value\)/);
assert.match(page, /name="gunmancer-\$\{group\}"/);
assert.match(page, /name="gunmancer-airblast"/);
assert.match(page, /sourceIcon: ability\.iconUrl/);
assert.match(page, /sourceIcon: GUNMANCER_AIRBLAST\.iconUrl/);
assert.match(page, /columnKey: "gunmancer-airblast",\s*sourceIcon: GUNMANCER_AIRBLAST\.iconUrl/);
assert.match(page, /const columns = model\.damageSources/);
assert.match(page, /column\.isStatusGroupStart \? "status-group-start" : ""/);
assert.match(page, /All Gunmancer attack damage instances, including secondary explosions, are modeled as crit-capable/);
assert.match(page, /separate secondary rates: Firebomb 0\.33\/s, Photon Condenser 4\/s, and Antimatter Accelerator 0\.5\/s/);
assert.match(page, /const dpsGroup = gunmancerDpsGroup\(\)/);
assert.match(page, /dpsGroup === "primary" \? \{ group: "Primary", ability: primary \} : \{ group: "Secondary", ability: secondary \}/);
assert.match(page, /buildOptions\.gunmancerAirblastTarget === dpsGroup/);
assert.match(page, /label: "Overall Damage"/);
assert.match(page, /label: "Elemental Damage"/);
assert.match(page, /label: "Eff\. Crit Multiplier"/);
assert.match(page, /label: "Instance Rate"/);
assert.match(page, /label: "Uptime"/);
assert.match(page, /const statusBox = \(status, rowsForStatus\) =>/);
assert.match(page, /statusSource && statusApplicationRate > 0/);
assert.match(page, /Attack Speed is applied to selected skills as a working model/);
assert.match(page, /const hasUnknownRate = componentEntries\.some\(entry => entry\.nonCriticalDps == null\)/);
assert.match(page, /const canCrit = target\.components\.some\(component => component\.canCrit === null\)/);
assert.match(page, /Gunmancer: Marksman is selected/);
assert.match(page, /id="calculation-content"/);
assert.match(page, /function renderCalculations\(\)/);
assert.match(page, /const UNIMPLEMENTED_DPS_MESSAGE = "I havent decided on how this class should produce a useful DPS number yet, lol"/);
assert.match(page, /configuration-empty">\$\{escapeHtml\(UNIMPLEMENTED_DPS_MESSAGE\)\}/);
assert.match(page, /calculation-empty">\$\{escapeHtml\(UNIMPLEMENTED_DPS_MESSAGE\)\}/);
assert.match(page, /const uptimePercent = value =>/);
assert.match(page, /formatted\.endsWith\("\.00"\) \? formatted\.slice\(0, -3\) : formatted/);
assert.match(page, /value: hand => uptimePercent\(hand\.damage\.uptime\)/);
assert.match(page, /const overallMultiplier = Number\(latestCalculation\.stats\.overallDamage \|\| 0\) \/ 100;/);
assert.match(page, /const elementalMultiplier = Number\(latestCalculation\.stats\[hand\.element\.damageStat\] \|\| 0\) \/ 100;/);
assert.match(page, /\.filter\(hand => hand\.enabled\)/);
assert.match(page, /calculatedHands\.length === 1 \? "single-hand" : "dual-hand"/);
assert.match(page, /data-element="\$\{hand\.element\.id\}"/);
assert.match(page, /physical.*damageStat: "physicalDamage"/);
assert.match(page, /lightning.*damageStat: "electricDamage"/);
assert.match(page, /\.damage-column\[data-element="electric"\] \{ --damage-color: var\(--electric\); \}/);
assert.match(page, /handName: "Flaming Hand", baseDamage: 30/);
assert.match(page, /handName: "Ice Hand", baseDamage: 30/);
assert.match(page, /handName: "Electric Hand", baseDamage: 30/);
assert.match(page, /handName: "Wind Blade", baseDamage: 30/);
assert.match(page, /handName: "Divine Hand", baseDamage: 35/);
assert.match(page, /handName: "Profane Hand", baseDamage: 20/);
assert.match(page, /const attackSpeedBase = hands\.length === 1 \? 1\.4 : 0\.8;/);
assert.match(page, /const attackSpeedMultiplier = Number\(latestCalculation\.stats\.attackSpeed \|\| 0\) \/ 100;/);
assert.match(page, /const sinistraStacks = count\("Twinmage-Hand-Boost-L"\);/);
assert.match(page, /const dextraStacks = count\("Twinmage-Hand-Boost-R"\);/);
assert.match(page, /const handDamageUpgradeActive = sinistraStacks > 0 \|\| dextraStacks > 0;/);
assert.match(page, /const handModifiers = position =>/);
assert.match(page, /const bonusPercent = positiveStacks \* 5 - negativeStacks \* 3;/);
assert.match(page, /const handDamageMultiplier = handModifiersForHand\.multiplier;/);
assert.match(page, /const handAttackSpeedMultiplier = handModifiersForHand\.multiplier;/);
assert.match(page, /attackSpeedBase \* attackSpeedMultiplier \* handAttackSpeedMultiplier/);
assert.match(page, /if \(stat === "attackSpeed"\) return `\$\{Number\(Number\(value\)\.toFixed\(2\)\)\}%`;/);
assert.match(page, /const instancesPerSecond = attackSpeedBase \* attackSpeedMultiplier \* handAttackSpeedMultiplier;/);
assert.match(page, /hand\.element\.baseDamage \* overallMultiplier \* elementalMultiplier \* handDamageMultiplier \* criticalMultiplier/);
assert.match(page, /const totalDamage = Math\.round\(unroundedDamage\);/);
assert.match(page, /const dps = totalDamage \* instancesPerSecond;/);
assert.match(page, /const totalDps = dps \* uptime;/);
assert.match(page, /data-exact-value="\$\{escapeHtml\(String\(row\.exact\(hand\)\)\)\}"/);
assert.match(page, /label: "Instance Rate"/);
assert.match(page, /key: "hand-damage", label: "Hand Damage"/);
assert.doesNotMatch(page, /damage-source/);
assert.doesNotMatch(page, /Hand damage overview|damage-calculation-note|damage-calculation-head/);
assert.match(page, /\.damage-table \.damage-data-col \{ width: 72px; \}/);
assert.match(page, /<col class="damage-label-col"><col class="damage-data-col" span="\$\{damageColumns\.length\}">/);
assert.match(page, /const pocketAbacusStacks = count\("Pocket_Abacus"\);/);
assert.match(page, /const rawCriticalChancePercent = Number\(latestCalculation\.stats\.criticalChance \|\| 0\);/);
assert.match(page, /const criticalChancePercent = pocketAbacusStacks > 0 \? 20 : rawCriticalChancePercent;/);
assert.match(page, /const criticalDamagePercent = Number\(latestCalculation\.stats\.criticalDamage \|\| 0\);/);
assert.match(page, /const criticalChance = Math\.max\(0, criticalChancePercent\) \/ 100;/);
assert.match(page, /const effectiveCriticalMultiplier = \(criticalDamageMultiplier - 1\) \* criticalChance \+ 1;/);
assert.match(page, /\.filter\(hand => hand\.element\.canCrit\)[\s\S]*const criticalHitsPerSecond = criticalInstanceRate \* criticalChance;/);
assert.match(page, /const criticalMultiplier = hand\.element\.canCrit \? effectiveCriticalMultiplier : 1;/);
assert.match(page, /label: "Crits per second"/);
assert.match(page, /<th colspan="2">Critical hits<\/th>/);
assert.equal((page.match(/statusChances: \{ burning: 0\.10 \}/g) || []).length, 1);
assert.match(page, /const BURNING = \{ baseStacks: 20, stacksPerSticky: 2, durationPerStack: 0\.5, bossApplicationPenalty: 3 \};/);
assert.match(page, /chance \/ attackSpeedMultiplier/);
assert.match(page, /sum \+ hand\.damage\.instancesPerSecond \* hand\.effectiveStatusChances\.burning/);
assert.match(page, /const burningStacks = BURNING\.baseStacks \+ count\("Sticky"\) \* BURNING\.stacksPerSticky;/);
assert.match(page, /const burningDuration = burningStacks \* BURNING\.durationPerStack;/);
assert.match(page, /Math\.min\(1, burningDuration \/ burningInterval\)/);
assert.match(page, /burningHands\.length \? `<section class="status-table-wrap" data-status="burning">/);
assert.match(page, /<th colspan="2">Status: Burning<\/th>/);
assert.match(page, /<div class="calculation-secondary">[\s\S]*crit-table-wrap[\s\S]*status-table-wrap/);
assert.match(page, /id: "burning", handName: "Burning", baseDamage: 25, damageStat: "fireDamage", canCrit: false, statusChances: \{\}/);
assert.match(page, /const instancesPerSecond = 0\.5;/);
assert.match(page, /const uptime = burningUptime;/);
assert.match(page, /const statusColumns = \[burningColumn, bleedingColumn\]\.filter\(Boolean\)/);
assert.match(page, /const triggeredColumns = \[chargedStrikeColumn\]\.filter\(Boolean\);/);
assert.match(page, /const damageColumns = \[\.\.\.attackSources, \.\.\.triggeredColumns, \.\.\.statusColumns\];/);
assert.match(page, /const masteryColumns = count\("Twinmage_Mastery"\) > 0 \? calculatedHands\.map/);
assert.match(page, /baseDamage: hand\.element\.baseDamage \* 0\.25/);
assert.match(page, /const instancesPerSecond = hand\.damage\.instancesPerSecond;/);
assert.match(page, /baseStatusChances: \{ \.\.\.hand\.baseStatusChances \}/);
assert.match(page, /effectiveStatusChances: \{ \.\.\.hand\.effectiveStatusChances \}/);
assert.match(page, /const attackSources = \[\.\.\.calculatedHands, \.\.\.masteryColumns\];/);
assert.match(page, /const weightedHandDamageMultiplier = \(sources, weight = hand => hand\.damage\.instancesPerSecond\) =>/);
assert.match(page, /const handDamageMultiplier = weightedHandDamageMultiplier\(attackSources\.filter\(hand => hand\.element\.canCrit\)\);/);
assert.match(page, /const burningHands = attackSources\.filter/);
assert.match(page, /const bleedingHands = attackSources\.filter/);
assert.match(page, /weightedHandDamageMultiplier\(burningHands, hand => hand\.damage\.instancesPerSecond \* hand\.effectiveStatusChances\.burning\)/);
assert.match(page, /weightedHandDamageMultiplier\(bleedingHands, hand => hand\.damage\.instancesPerSecond \* hand\.effectiveStatusChances\.bleeding\)/);
assert.match(page, /const chargedStrikeStacks = count\("Charged_Strike"\);/);
assert.match(page, /baseDamage: 25 \+ Math\.max\(0, chargedStrikeStacks - 1\) \* 10/);
assert.match(page, /damageStat: "physicalDamage", canCrit: false, statusChances: \{\}/);
assert.match(page, /const instancesPerSecond = criticalHitsPerSecond;/);
assert.match(page, /position: "Upgrade effect", columnKey: "charged-strike"/);
assert.match(page, /hand\.isTriggeredEffect \? \["calc:crit:rate"\]/);
assert.match(page, /sourceUpgradeId: "Twinmage_Mastery"/);
assert.match(page, /sourceUpgradeId: "Charged_Strike"/);
assert.match(page, /data-calculation-source-upgrade=/);
assert.match(page, /calculation-tooltip-upgrade-icon/);
assert.match(page, /sourceUpgrade\.effect/);
assert.match(page, /sourceIcon: hand\.element\.image/);
assert.match(page, /data-calculation-source-icon=/);
assert.match(page, /calculation-tooltip-source-icon/);
assert.match(page, /hand\.element\.canCrit \? twoDecimals\(hand\.damage\.criticalMultiplier\) : "-"/);
assert.match(page, /hand\.isStatusGroupStart \? "status-group-start" : ""/);
assert.match(page, /\.damage-column\.status-group-start \{ border-left: 3px solid rgba\(var\(--class-rgb\), \.72\); \}/);
assert.equal((page.match(/statusChances: \{ bleeding: 0\.10 \}/g) || []).length, 1);
assert.match(page, /const BLEEDING = \{ baseStacks: 16, stacksPerSticky: 2, durationPerStack: 0\.8, bossApplicationPenalty: 3 \};/);
assert.match(page, /burning: \{ upgradeId: "Fire_Aspect", chancePerStack: 0\.05 \}/);
assert.match(page, /bleeding: \{ upgradeId: "Cutting_Edge", chancePerStack: 0\.10 \}/);
assert.match(page, /frozen: \{ upgradeId: "Frost_Aspect", chancePerStack: 0\.05 \}/);
assert.match(page, /weakened: \{ upgradeId: "Luminous_Aspect", chancePerStack: 0\.05 \}/);
assert.match(page, /breached: \{ upgradeId: "Shadow_Aspect", chancePerStack: 0\.05 \}/);
assert.doesNotMatch(page, /paralyzed: \{ upgradeId:/);
assert.match(page, /chance \+ \(bonus \? count\(bonus\.upgradeId\) \* bonus\.chancePerStack : 0\)/);
assert.match(page, /Object\.entries\(baseStatusChances\)/);
assert.match(page, /hand\.baseStatusChances\.burning \* 100/);
assert.match(page, /hand\.baseStatusChances\.bleeding \* 100/);
assert.match(page, /const burningRawUptime = bossAdjustedBurningRate > 0 \? burningDuration \/ burningInterval : 0;/);
assert.match(page, /const bleedingRawUptime = bossAdjustedBleedingRate > 0 \? bleedingDuration \/ bleedingInterval : 0;/);
assert.match(page, /status-uncapped-uptime/);
assert.match(page, /`100% <span class="status-uncapped-uptime">/);
assert.match(page, /capped at 100%/);
assert.match(page, /\.damage-column\[data-element="physical"\] \{ --damage-color: var\(--physical\); \}/);
assert.doesNotMatch(page, /\.stat-row\[data-stat="physicalDamage"\] \.value \{ color: var\(--physical\); \}/);
assert.match(page, /\.stat-list \{[\s\S]*?font-style: normal;/);
assert.match(page, /sum \+ hand\.damage\.instancesPerSecond \* hand\.effectiveStatusChances\.bleeding/);
assert.match(page, /const bleedingStacks = BLEEDING\.baseStacks \+ count\("Sticky"\) \* BLEEDING\.stacksPerSticky;/);
assert.match(page, /const bleedingDuration = bleedingStacks \* BLEEDING\.durationPerStack;/);
assert.match(page, /Math\.min\(1, bleedingDuration \/ bleedingInterval\)/);
assert.match(page, /id: "bleeding", name: "Physical", handName: "Bleeding", baseDamage: 25, damageStat: "physicalDamage", canCrit: false/);
assert.match(page, /const instancesPerSecond = 1 \/ 0\.8;/);
assert.match(page, /<th colspan="2">Status: Bleeding<\/th>/);
assert.match(page, /Pocket Abacus: every fifth damage instance is guaranteed critical/);
assert.match(page, /effective chance = 20\.00% \(other crit chance modifiers ignored\)/);
assert.equal((page.match(/statusChances: \{ (?:frozen|paralyzed|weakened|breached): 0\.10 \}/g) || []).length, 4);
assert.match(page, /const NON_DAMAGE_STATUS_DEFINITIONS = \[/);
assert.match(page, /const nonDamageStatuses = NON_DAMAGE_STATUS_DEFINITIONS\.map/);
assert.match(page, /\.filter\(status => status\.sources\.length\)/);
assert.match(page, /const nonDamageStatusRows = status =>/);
assert.match(page, /label: "Stacks per application", value: "\?"/);
assert.match(page, /label: "Uptime", value: "\?"/);
assert.match(page, /Status: \$\{escapeHtml\(status\.name\)\}/);
assert.match(page, /id: "frozen", name: "Frozen", baseStacks: 8, stacksPerSticky: 2, durationPerStack: \.6, bossApplicationPenalty: 10/);
assert.match(page, /id: "paralyzed", name: "Paralyzed", baseStacks: 8, stacksPerSticky: 2, durationPerStack: \.3, bossApplicationPenalty: 10/);
assert.match(page, /id: "weakened", name: "Weakened", baseStacks: 10, stacksPerSticky: 2, durationPerStack: \.8, bossApplicationPenalty: 2/);
assert.match(page, /id: "breached", name: "Breached", baseStacks: 10, stacksPerSticky: 2, durationPerStack: \.7, bossApplicationPenalty: 2/);
assert.equal((page.match(/Bosses likely build up resistance against this status effect over time!/g) || []).length, 2);
assert.match(page, /class="status-note" colspan="2"/);
assert.match(page, /const combinedTotalDps = damageSources\.filter\(source => !source\.excluded\)[\s\S]*?\.reduce\(\(sum, source\) => sum \+ source\.damage\.totalDps, 0\);/);
assert.match(page, /id="combined-dps-summary"[^>]*aria-live="polite">0\.00<\/strong>/);
assert.match(page, /function updateCombinedDpsSummary\(value, visible = true\)/);
assert.match(page, /updateCombinedDpsSummary\(0, false\);/);
assert.match(page, /updateCombinedDpsSummary\(model\.combinedTotalDps\);/);
assert.match(page, /<th scope="row" class="damage-combined-label">Combined DPS<\/th>/);
assert.match(page, /calculationAttributes\("damage:combined:total-dps"/);
assert.match(page, /const combinedDpsBreakdown = Object\.values\(damageColumns\.reduce/);
assert.match(page, /data-calculation-damage-type=/);
assert.match(page, /data-calculation-breakdown=/);
assert.match(page, /calculation-damage-breakdown-row/);
assert.match(page, /id="calculation-tooltip" role="tooltip"/);
assert.match(page, /data-calculation-key=/);
assert.match(page, /data-calculation-formula=/);
assert.match(page, /data-calculation-refs=/);
assert.match(page, /refs: \(\) => \["stat:overallDamage"\]/);
assert.match(page, /refs: hand => hand\.element\.canCrit \? \["calc:crit:effective"\] : \[\]/);
assert.match(page, /function highlightCalculationReferences\(refs\)/);
assert.match(page, /function positionCalculationTooltip\(clientX, clientY\)/);
assert.match(page, /\.calculation-reference/);
assert.match(page, /const sourceFormula = hand =>/);
assert.match(page, /Crit: \$\{hand\.element\.canCrit \? "Yes" : "No"\}/);
assert.match(page, /% ÷ \$\{twoDecimals\(attackSpeedMultiplier \* 100\)\}% AS = \$\{twoDecimals\(hand\.effectiveStatusChances\[status\] \* 100\)\}%/);
assert.match(page, /hand\.baseStatusChances\.burning \* 100\).*attackSpeedMultiplier \* 100/);
assert.match(page, /calculationAttributes\(`source:\$\{hand\.columnKey\}`, sourceFormula\(hand\)\)/);
assert.match(page, /tooltip\.style\.setProperty\("--tooltip-accent", accent\)/);
assert.match(page, /calculation-tooltip-head/);
assert.match(page, /calculation-tooltip-expression/);
assert.match(page, /Non-crit: \$\{hand\.element\.baseDamage\}/);
assert.match(page, /Crit: \$\{twoDecimals\(bareDamage\)\} × \$\{twoDecimals\(criticalDamageMultiplier\)\}/);
assert.match(page, /"calc:crit:damage", "stat:criticalDamage"/);
assert.match(page, /id: "physical", name: "Physical", handName: "Charged Strike"/);
assert.match(page, /id="dps-ranking-list"/);
assert.match(page, /function renderDpsRanking\(\)/);
assert.match(page, /Calculating 0 \/ \$\{candidates\.length\}/);
assert.match(page, /Calculating \$\{index\} \/ \$\{candidates\.length\}/);
assert.match(page, /requestAnimationFrame\(processChunk\)/);
assert.match(page, /cancelAnimationFrame\(dpsRankingFrame\)/);
assert.match(page, /restoreCounts\(dpsRankingSnapshot\)/);
assert.match(page, /latestCalculation = calculateStats\(\);/);
assert.match(page, /rankingSection\.hidden = !dpsRankingVisible/);
assert.match(page, /listElement\.innerHTML = ""/);
assert.doesNotMatch(page, /dps-ranking-increase">\$\{sign\}\$\{twoDecimals\(result\.delta\)\}/);
assert.match(page, /const candidateDps = renderCalculations\(\{ render: false \}\)/);
assert.match(page, /const primaryActivationRate = primaryAbility\?\.interval > 0 \? attackSpeedMultiplier \/ primaryAbility\.interval : 0/);
assert.match(page, /instancesPerSecond: primaryActivationRate,[\s\S]*isFlamingSpirit: true/);
assert.match(page, /const preChargedAttackSources = \[\.\.\.attackColumns, \.\.\.classTriggeredColumns, \.\.\.\(flamingSpiritColumn \? \[flamingSpiritColumn\] : \[\]\)\]/);
assert.match(page, /const criticalHitsPerSecond = criticalSources\.reduce\(\(sum, column\) => sum \+ column\.damage\.instancesPerSecond, 0\) \* criticalChance/);
assert.match(page, /baseDamage: 25 \+ 10 \* Math\.max\(0, chargedStrikeStacks - 1\)/);
assert.match(page, /instancesPerSecond: criticalHitsPerSecond,[\s\S]*isChargedStrike: true/);
assert.match(page, /const primaryAbility = gunmancerAbility\(buildOptions\.gunmancerPrimary, "primary"\)/);
assert.match(page, /results\.sort\(\(a, b\) => b\.delta - a\.delta/);
assert.match(page, /data-dps-upgrade-id/);
assert.match(page, /function restoreCounts\(snapshot\)/);
assert.match(page, /id="dps-ranking-toggle"[^>]*aria-expanded="false">Show sorted by DPS<\/button>/);
assert.match(page, /id="dps-ranking-list" hidden/);
assert.match(page, /class="dps-ranking"[^>]*hidden/);
assert.match(page, /let dpsRankingVisible = false/);
assert.match(page, /dpsRankingVisible \? "Hide sorted by DPS" : "Show sorted by DPS"/);
assert.match(page, /if \(run !== dpsRankingRun \|\| !dpsRankingVisible\)/);
assert.doesNotMatch(page, /Estimated DPS change from adding one stack/);
assert.match(page, /id="catalog"/);
assert.match(page, /\$\("#catalog"\)\.addEventListener\("click"/);
assert.match(page, /instanceRate: 2/);
assert.match(page, /const flamingSpiritColumn = count\("Flaming_Spirit"\)/);
assert.match(page, /firstStackDamage: 16, additionalStackDamage: 8/);
assert.match(page, /const instancesPerSecond = primaryHand\.damage\.instancesPerSecond/);
assert.match(page, /const overallMultiplier = 1;/);
assert.match(page, /sourceUpgradeId: "Flaming_Spirit"/);
assert.match(page, /upgradeId: "Flaming_Spirit".+firstStackDamage: 16, additionalStackDamage: 8/);
assert.match(page, /upgradeId: "Frozen_Heart".+firstStackDamage: 18, additionalStackDamage: 9.+statusId: "frozen".+statusChance: \.10/);
assert.match(page, /overallDamageApplies: false/);
assert.match(page, /hand\.damage\.overallDamageApplies === false \? "-"/);
assert.match(page, /const instancesPerSecond = 2;/);
assert.match(page, /damage-value-unknown/);
assert.match(page, /Does not apply to this damage source/);
assert.match(page, /const calculateDamageValues =/);
assert.match(page, /averageDamageRow\.label = "Average Damage"/);
assert.match(page, /Non-crit: \$\{hand\.damage\.nonCriticalDamage\}/);
assert.match(page, /Crit: \$\{hand\.damage\.criticalDamage\}/);
assert.match(page, /Non-crit: \$\{bareDamageFormula\}/);
assert.match(page, /Crit: \$\{bareDamageFormula\} ×/);
assert.match(page, /Average: \$\{hand\.damage\.nonCriticalDamage\}/);
assert.match(page, /const CLASS_DAMAGE_SOURCES =/);
assert.match(page, /Gunmancer: \[\]/);
assert.match(page, /const CONDITIONAL_UPGRADE_RULES =/);
assert.match(page, /Gunmancer_Overcharged: \{ requiresAbility: \{ group: "primary", id: "va11" \}/);
assert.match(page, /Gunmancer_Marksman: \{ requiresAbility: \{ group: "primary", id: "va11" \}/);
assert.match(page, /Flaming_Spirit: \{ blockedBy: "frost"/);
assert.match(page, /Frozen_Heart: \{ blockedBy: "fire"/);
assert.match(page, /Curse_of_Wrath: \{ blockedBy: "luminous"/);
assert.match(page, /Benison_of_Purification: \{ blockedBy: "shadow"/);
assert.match(page, /Strength: \{ requires: "physical"/);
assert.match(page, /Fire_Aspect: \{ requires: "fire"/);
assert.match(page, /function getDamageSources\(\)/);
assert.match(page, /if \(selectedClass === "Gunmancer"\)/);
assert.match(page, /conditional-unavailable/);
assert.match(page, /function isUpgradeConditionallyAvailable\(upgrade\)/);
assert.match(page, /filteredUpgrades\(\)\.sort\(\(a, b\) =>/);
assert.match(page, /const familyOrder = family => family === "Mobility Crystal" \? 0 : family === "Endurance Crystal" \? 1 : 2/);
assert.match(page, /familyOrder\(a\.family\) - familyOrder\(b\.family\) \|\| a\.globalId - b\.globalId/);
assert.match(page, /renderCatalog\(\);\n        renderDpsRanking\(\);\n        updateShareWidget\(\);/);
assert.match(page, /class="application-breakdown"/);
assert.match(page, /<th>Instances\/s<\/th><th>Chance<\/th><th>Applications\/s<\/th>/);
assert.match(page, /data-application-breakdown=/);
assert.match(page, /const statusMarkup = model\.statuses\.map/);
assert.match(page, /sources: status\.sources\.map/);
assert.match(page, /applicationsPerSecond: rateNumber\(source\.applicationsPerSecond\)/);
assert.match(page, /1 ÷ \$\{escapeHtml\(applicationBreakdown\.total\)\} = \$\{escapeHtml\(applicationBreakdown\.interval\)\} s/);

console.log("Build option regression tests passed.");
